@baseUrl = http://localhost:3001/
@id = 8
@token1 = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyZW5kZWwiLCJpZCI6MSwiaWF0IjoxNjgxNDU5NzIyfQ.P3kfzGDTd6fYW5zhfeL3m7GdKXSp6ThDrL1FQbxCgkM
@token2 = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBwYW4iLCJpZCI6MywiaWF0IjoxNjgxNDYwOTc5fQ.8gQD0ZLXEG7ZVeOsqj3FkBtUlfxm2hIeTh2fMwQxGFg

### Add blog
POST {{baseUrl}}api/blogs
Authorization: {{token2}}
Content-Type: application/json

{
    "title": "How to dance",
    "author": "Miley Cyrus",
    "url": "www.miley.com"
}

### Update likes
PUT {{baseUrl}}api/blogs/{{id}}
Content-Type: application/json

{
  "likes": 100
}

### Delete blog
DELETE {{baseUrl}}api/blogs/{{id}}
Authorization: {{token1}}

### Test faulty blog
POST {{baseUrl}}api/blogs
Authorization: {{token1}}
Content-Type: application/json

{
    "title": "Hello with Comment 2",
    "author": "Commenter 2"
}