@baseUrl = http://localhost:3003/
@testId = 636cf684089d73f0db2d8832

### Delete
DELETE {{baseUrl}}api/blogs/{{testId}}

### Add person
POST {{baseUrl}}api/blogs
Content-Type: application/json

{
    "title": "Hello World 5",
    "author": "Peter Pan 5",
    "url": "www.test5.com",
    "likes": 10
}

### Add person without likes
POST {{baseUrl}}api/blogs
Content-Type: application/json

{
    "title": "Hello World 5",
    "author": "Peter Pan 5",
    "likes": 10
}