@baseUrl = http://localhost:3003/
@testId = 63724bf80d739d927ae64c32

### Delete blog
DELETE {{baseUrl}}api/blogs/{{testId}}

### Add blog
POST {{baseUrl}}api/blogs
Content-Type: application/json

{
    "title": "Hello World 5",
    "author": "Peter Pan 5",
    "url": "www.test5.com",
    "likes": 10
}

### Add blog without likes
POST {{baseUrl}}api/blogs
Content-Type: application/json

{
    "title": "Hello World 5",
    "author": "Peter Pan 5",
    "likes": 10
}

### Update blog
PUT {{baseUrl}}api/blogs/{{testId}}
Content-Type: application/json

{
    "title": "Hello World Updated",
    "author": "Peter Pan Updated",
    "url": "www.update.com",
    "likes": 100
}